package com.oreon.cerebrum.charts;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Date;

import com.google.common.base.Objects;

import javax.persistence.*;
import org.hibernate.validator.*;

import com.google.common.base.Objects;

import org.apache.commons.lang.builder.ReflectionToStringBuilder;
import org.apache.commons.lang.builder.ToStringStyle;

import org.apache.solr.analysis.LowerCaseFilterFactory;
import org.apache.solr.analysis.SnowballPorterFilterFactory;
import org.apache.solr.analysis.StandardTokenizerFactory;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.Formula;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.Filters;
import org.hibernate.annotations.Cascade;

import org.hibernate.search.annotations.AnalyzerDef;
import org.hibernate.search.annotations.Analyzer;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Boost;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Parameter;
import org.hibernate.search.annotations.TokenFilterDef;
import org.hibernate.search.annotations.TokenizerDef;
import org.hibernate.search.annotations.ContainedIn;
import org.hibernate.search.annotations.IndexedEmbedded;

import org.hibernate.annotations.Filter;

import org.hibernate.validator.constraints.*;
import javax.validation.constraints.*;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import org.jboss.seam.annotations.Name;

import org.witchcraft.model.support.audit.Auditable;

import org.witchcraft.utils.*;

import org.witchcraft.base.entity.FileAttachment;
import org.witchcraft.base.entity.BaseEntity;

import com.oreon.cerebrum.ProjectUtils;

//Impl 

/**
 * This file is generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 *
 */

/**
 * 
 *
 */

@MappedSuperclass
public class ChartItemBase extends BaseEntity {
	private static final long serialVersionUID = -1377884752L;

	@NotNull
	@Length(min = 1, max = 250)
	@Column(unique = false)
	@Field(index = Index.YES)
	@Analyzer(definition = "entityAnalyzer")
	protected String name

	;

	@Column(unique = false)
	protected Integer duration

	;

	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@JoinColumn(name = "chart_id", nullable = false, updatable = true)
	protected Chart chart

	;

	@Column(unique = false)
	protected TimeEnumeration frequencyPeriod

	;

	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
	@JoinTable(name = "chartItems_trackedVitals", joinColumns = @JoinColumn(name = "chartItems_ID"), inverseJoinColumns = @JoinColumn(name = "trackedVitals_ID"))
	private Set<com.oreon.cerebrum.patient.TrackedVital> trackedVitals = new HashSet<com.oreon.cerebrum.patient.TrackedVital>();

	public void addTrackedVital(
			com.oreon.cerebrum.patient.TrackedVital trackedVital) {

		this.trackedVitals.add(trackedVital);
	}

	@Transient
	public List<com.oreon.cerebrum.patient.TrackedVital> getListTrackedVitals() {
		return new ArrayList<com.oreon.cerebrum.patient.TrackedVital>(
				trackedVitals);
	}

	@Transient
	public String getListTrackedVitalsAsString() {
		StringBuilder result = new StringBuilder();

		List<com.oreon.cerebrum.patient.TrackedVital> tempList = getListTrackedVitals();
		int count = 0;
		for (com.oreon.cerebrum.patient.TrackedVital trackedVital : tempList) {
			++count;
			result.append(trackedVital.getDisplayName());
			if (count < tempList.size())
				result.append(", ");
		}

		return result.toString();
	}

	//JSF Friendly function to get count of collections
	public int getTrackedVitalsCount() {
		return trackedVitals.size();
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getName() {

		return name;

	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	public Integer getDuration() {

		return duration;

	}

	public void setChart(Chart chart) {
		this.chart = chart;
	}

	public Chart getChart() {

		return chart;

	}

	public void setFrequencyPeriod(TimeEnumeration frequencyPeriod) {
		this.frequencyPeriod = frequencyPeriod;
	}

	public TimeEnumeration getFrequencyPeriod() {

		return frequencyPeriod;

	}

	public void setTrackedVitals(
			Set<com.oreon.cerebrum.patient.TrackedVital> trackedVitals) {
		this.trackedVitals = trackedVitals;
	}

	public Set<com.oreon.cerebrum.patient.TrackedVital> getTrackedVitals() {
		return trackedVitals;
	}

	@Transient
	public String getDisplayName() {
		try {
			return name;
		} catch (Exception e) {
			return "Exception - " + e.getMessage();
		}
	}

	//Empty setter , needed for richfaces autocomplete to work 
	public void setDisplayName(String name) {
	}

	/** This method is used by hibernate full text search - override to add additional fields
	 * @see org.witchcraft.model.support.BaseEntity#retrieveSearchableFieldsArray()
	 */
	@Override
	public List<String> listSearchableFields() {
		List<String> listSearchableFields = new ArrayList<String>();
		listSearchableFields.addAll(super.listSearchableFields());

		listSearchableFields.add("name");

		return listSearchableFields;
	}

	@Field(index = Index.YES, name = "searchData")
	@Analyzer(definition = "entityAnalyzer")
	public String getSearchData() {
		StringBuilder builder = new StringBuilder();

		builder.append(getName() + " ");

		if (getChart() != null)
			builder.append("chart:" + getChart().getDisplayName() + " ");

		return builder.toString();
	}

	/*
	<param name="chartId" value="#{chartId}" />
	
	 */

}
