package com.oreon.cerebrum.reports;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

/**
 * This file is an Entity Class generated by Witchcraftmda.
 * DO NOT MODIFY any changes will be overwritten with the next run of the code generator.
 */

public class EmployeesByDepartment extends EmployeesByDepartmentBase
		implements
			java.io.Serializable {
	private static final long serialVersionUID = -3758591L;
}
